comments = true
math = true

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
toc = true

favicon = "/images/favicon.ico"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "blog"

# SEO keywords and description for your site.
keywords = "hugo, blog, cybersecurity"

description = "projects and things"

author = "Micah Cessna"


hugourl = "https://gohugo.io/"
hugomask = "Hugo"
themeurl = "https://github.com/zEttOn86/hugo_theme_windy"
thememask = "Windy"
themedev = "zEttOn86"
