baseURL = 'https://cessna.io/'
languageCode = 'en-us'
title = 'cessna.io'
theme = 'hugo-theme-nightfall'

[params]
user = 'micah'
hostname = 'cessna.io'

  [params.author]
    name = "Micah Cessna"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/blog"

  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

